#version: '3.11'
services:
  db:
    image: postgres:16
    container_name: devops_db
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tasknet
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  backend:
    build:
      context: ./backend
    container_name: devops_backend
    ports:
      - "5000:5000"
    networks:
      - tasknet
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: devops_frontend
    ports:
      - "3000:80"
    networks:
      - tasknet

networks:
  tasknet:

volumes:
  postgres_data:
